package com.trainingapp.api.model;

public enum GrupoMuscular {
	PEITO, COSTAS, LOMBAR, TRAPEZIO, OMBROS, BICEPS, TRICEPS, ANTEBRACO, ABDOMEN,
	QUADRICEPS, POSTERIORES, GLUTEOS, ADUTORES, ABDUTORES, PANTURRILHA, PESCOCO,
	CORPO_INTEIRO, CARDIO
}
