spring.application.name=trainingapp-api
spring.profiles.default=dev
spring.jpa.open-in-view=false
trainingapp.cors.origens=http://localhost:4200
trainingapp.catalogo.importar=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
